# Use official Python image
FROM python:3.12-slim

# Set working directory inside the container
WORKDIR /app

# Copy project files into the container
COPY . .

# Run the Python app
CMD ["python", "main.py"]

